### ISSUE TITLE
Update the bee emoji

### ISSUE THREAD

**Issue by lavelle** [googlei18n/noto-emoji#108]
Hello,

Looks like the bee SVG is out of date. It shows the old Android 6 emoji: https://github.com/googlei18n/noto-emoji/blob/master/svg/emoji_u1f41d.svg

The new one should look like:

http://emojipedia-us.s3.amazonaws.com/cache/02/5e/025e981c27aecee4d1d5abb15d0d9e05.png

Could you update the svg file to have the latest graphic?

Thanks in advance!

🐝🐝🐝🐝🐝

**Comment by dougfelt** [comment]
Most of the SVG data has been updated and this should be current now.
