### ISSUE TITLE
Legacy PUA emojis

### ISSUE THREAD

**Issue by Crissov** [googlei18n/noto-emoji#115]
I found some code in the repository that handles legacy Google PUA codes for the ten original emoji flags and for keycaps. To view some old data that I either do not want to or cannot convert to proper Unicode codepoints, it would be nice to build a (non-default) version of the font that supported more and other PUA codes. Every Japanese carrier had their own (and Apple shared a set with Softbank). 

## Example: Thumbs Up 

| Unicode | Apple&nbsp;iOS&nbsp;/<br> Softbank&nbsp;/<br> Yahoo&nbsp;/<br> Disney&nbsp;/<br> Vodafone&nbsp;/<br> J&#x2011;Phone | KDDI au EZweb (a) | KDDI au EZweb (b) | NTT Docomo i&#x2011;mode&nbsp;/<br> Willcom&nbsp;/<br> E&#x2011;Mobile | Google Gmail &hellip; |
|----|----|----|----|----|----|
| U+1F44D &#x1F44D; | U+E25A &#xE25A; | U+E4F9 &#xE4F9; | U+EFD2 &#xEFD2; | U+E727 &#xE727; | U+FEB97 &#xFEB97; |

I could provide a file with these mappings, but I'm not sure how and where to include it in the code, so cannot really write a pull request myself &ndash; unless someone could provide some helpful pointers.

**Comment by dougfelt** [comment]
Sorry, forgot about this.

If you want to make modifications for your own use, you can try adding the
mappings to emoji_aliases.txt. What I don't remember off the top of my head
is whether the build will generate empty default glyphs for the PUA
codepoints. I haven't checked.

**Comment by dougfelt** [comment]
@crissov did you try editing emoji_aliases.txt?

**Comment by Crissov** [comment]
Like so? https://github.com/Crissov/noto-emoji/blob/legacy-pua/emoji_aliases.txt

**Comment by dougfelt** [comment]
Yeah, that's the idea.  Have you tried building a font with this and testing it?

Since you don't sort by the alias codepoint I can't tell if any of them appear more than once.  I think the last one mentioned would win in that case.  That's the thing with PUA, anyone can use any of them for anything.

**Comment by Crissov** [comment]
I have not build a font yet.

Most codepoints between U+E501 and U+E537 appear twice, should probably remove the rare KDDIa variants.

**Comment by dougfelt** [comment]
Closing this.  I don't think it's something we want to do.
