### ISSUE TITLE
Some SVG images are not updated

### ISSUE THREAD

**Issue by dougfelt** [googlei18n/noto-emoji#119]
The following svg images are not current with the png/128 directory.  I have not checked to see which are present but not updated, and which are missing.  This lists those images that contained embedded bitmaps when generating the svg from .ai files.  Many of these images also had display issues.

emoji_u2648.svg
emoji_u1f321.svg
emoji_u1f34c.svg
emoji_u1f35b.svg
emoji_u1f377.svg
emoji_u1f3f5.svg
emoji_u1f468_1f3fb_200d_1f680.svg
emoji_u1f468_1f3fc_200d_1f680.svg
emoji_u1f468_1f3fd_200d_1f680.svg
emoji_u1f468_1f3fe_200d_1f680.svg
emoji_u1f468_1f3ff_200d_1f680.svg
emoji_u1f468_200d_1f680.svg
emoji_u1f469_1f3fb_200d_1f680.svg
emoji_u1f469_1f3fc_200d_1f680.svg
emoji_u1f469_1f3fd_200d_1f680.svg
emoji_u1f469_1f3fe_200d_1f680.svg
emoji_u1f469_1f3ff_200d_1f680.svg
emoji_u1f469_200d_1f680.svg
emoji_u1f47c_1f3fb.svg
emoji_u1f47c_1f3fc.svg
emoji_u1f47c_1f3fd.svg
emoji_u1f47c_1f3fe.svg
emoji_u1f47c_1f3ff.svg
emoji_u1f47c.svg
emoji_u1f4f8.svg
emoji_u1f4ff.svg
emoji_u1f5c2.svg
emoji_u1f5de.svg
emoji_u1f644.svg
emoji_u1f6eb.svg
emoji_u1f6ec.svg
emoji_u1f6f0.svg
emoji_u1f6f4.svg
emoji_u1f6f5.svg
emoji_u1f6f6.svg
emoji_u1f911.svg
emoji_u1f912.svg
emoji_u1f914.svg
emoji_u1f915.svg
emoji_u1f917.svg
emoji_u1f918.svg
emoji_u1f922.svg
emoji_u1f923.svg
emoji_u1f924.svg
emoji_u1f942.svg
emoji_u1f943.svg
emoji_u1f94a.svg
emoji_u1f952.svg
emoji_u1f953.svg
emoji_u1f981.svg
emoji_u1f989.svg
emoji_u1f98a.svg
emoji_u1f98f.svg
emoji_u1f991.svg

**Comment by asturur** [comment]
i m open to fix the conversion process from illustrator to svg, or fix manually broken svgs if you can provide them. I need this set of emoticon and i can spend some time over it.

**Comment by DeeDeeG** [comment]
Thanks for these.

I noticed that some of the ones released today have extra art in them, which is giving me some trouble, but only when using them in an SVG font. (For some reason the different versions are being shown next to each-other.)

If I can be of help with this, I'd be interested.

I can find which ones have extra components, and possibly even edit them out with a text editor or other SVG editing software.

I concur with asturur, that there is an interest in seeing these, and a will to work on them a bit.

Again, thanks for getting these into the repo, it's much appreciated.

**Comment by dougfelt** [comment]
Sorry to hear there's extraneous data in other of the svg files.  I only did a scan for embedded bitmaps.

As I mentioned on another bug report, our main issue is that these files are generated from internal AI files used by our designers.  Modifying the SVG files directly means we can't take further changes from the designers without losing these changes.  It also leaves open the possibility that the SVG and PNG files can diverge, which has plagued us in the past (color/translucency modifications made to one but not the other, as an example).  I'm trying to figure out some way to take fixes since I'd like this set to be complete.

In the meantime a list of files with issues would be helpful.

**Comment by brawer** [comment]
Curious, why do the designers work with AI instead of SVG files? Would there be any disadvantages if the internal sources were kept in SVG instead of AI format? (Adobe Illustrator can directly edit SVG files, so there would be no tooling change for the designers; but there’d be no conversion step anymore).

**Comment by asturur** [comment]
The main disadavantage i can tell is that if you work with illustrator, SVG support is not good in import and is not perfect in output ( you also notice from the svg quality of those exported emoticons ).

I do not think illustrator edits svg, i think it imports them everytime.

@dougfelt if there is a chance to have those missing 54 emoticons, even with bad svg to fix manually, i would love to have them.

**Comment by DeeDeeG** [comment]
I found most of the problems. (There might be a few I missed, of course.) Here's the ~gist™~ .CSV: [link](https://gist.github.com/DeeDeeG/67c5ee45a6617629c41bb44c5bcc975e)

**Comment by asturur** [comment]
oh so this csv list the missing and the thing to fix. i guess i can start fixing them.

- [ ] emoji_u2648.svg
- [ ] emoji_u1f321.svg
- [ ] emoji_u1f34c.svg
- [ ] emoji_u1f35b.svg
- [ ] emoji_u1f377.svg
- [ ] emoji_u1f3f5.svg
- [ ] emoji_u1f468_1f3fb_200d_1f680.svg
- [ ] emoji_u1f468_1f3fc_200d_1f680.svg
- [ ] emoji_u1f468_1f3fd_200d_1f680.svg
- [ ] emoji_u1f468_1f3fe_200d_1f680.svg
- [ ] emoji_u1f468_1f3ff_200d_1f680.svg
- [ ] emoji_u1f468_200d_1f680.svg
- [ ] emoji_u1f469_1f3fb_200d_1f680.svg
- [ ] emoji_u1f469_1f3fc_200d_1f680.svg
- [ ] emoji_u1f469_1f3fd_200d_1f680.svg
- [ ] emoji_u1f469_1f3fe_200d_1f680.svg
- [ ] emoji_u1f469_1f3ff_200d_1f680.svg
- [ ] emoji_u1f469_200d_1f680.svg
- [ ] emoji_u1f47c_1f3fb.svg
- [ ] emoji_u1f47c_1f3fc.svg
- [ ] emoji_u1f47c_1f3fd.svg
- [ ] emoji_u1f47c_1f3fe.svg
- [ ] emoji_u1f47c_1f3ff.svg
- [ ] emoji_u1f47c.svg
- [ ] emoji_u1f4f8.svg
- [ ] emoji_u1f4ff.svg
- [ ] emoji_u1f5c2.svg
- [ ] emoji_u1f5de.svg
- [ ] emoji_u1f644.svg
- [ ] emoji_u1f6eb.svg
- [ ] emoji_u1f6ec.svg
- [ ] emoji_u1f6f0.svg
- [ ] emoji_u1f6f4.svg
- [ ] emoji_u1f6f5.svg
- [ ] emoji_u1f6f6.svg
- [ ] emoji_u1f911.svg
- [ ] emoji_u1f912.svg
- [ ] emoji_u1f914.svg
- [ ] emoji_u1f915.svg
- [ ] emoji_u1f917.svg
- [X] emoji_u1f918.svg
- [ ] emoji_u1f922.svg
- [ ] emoji_u1f923.svg
- [ ] emoji_u1f924.svg
- [ ] emoji_u1f942.svg
- [ ] emoji_u1f943.svg
- [ ] emoji_u1f94a.svg
- [ ] emoji_u1f952.svg
- [ ] emoji_u1f953.svg
- [ ] emoji_u1f981.svg
- [ ] emoji_u1f989.svg
- [ ] emoji_u1f98a.svg
- [ ] emoji_u1f98f.svg
- [ ] emoji_u1f991.svg

**Comment by DeeDeeG** [comment]
Yes, I went through the full emoji chart [here](http://unicode.org/emoji/charts/full-emoji-list.html) and looked for anything that had any errors.

I have fixed everything in that list, and a bit more as well, at my own repository, if you'd like to use the images I created, but if there's something you would change differently or you want to do it independently by all means go for it. Here is my repo with changes: https://github.com/DeeDeeG/noto-color-emoji-font/tree/cleanup/assets/noto-color-emoji-svg/cleaned

(I didn't list in my CSV any emoji with seams between two shapes, because there were too many to easily list, and because it was taking too long to both fix the emoji and update the list. If the full list is desired, I can make it.)

**Comment by asturur** [comment]
thanks i ll cherry pick them.

**Comment by DeeDeeG** [comment]
I noticed there is still a minor issue with fill colors in a couple of the "person shrugging" emoji so I'll fix those soon.

**Comment by dougfelt** [comment]
This is fixed, except region flags and rainbow flag still lack SVG versions.  Will close this and open another issue for those.
