### ISSUE TITLE
Missing U+1F595

### ISSUE THREAD

**Issue by brawer** [googlei18n/noto-emoji#12]
As noticed by @roubert, U+1F595 seems to be missing from Noto Emoji.

**Comment by roozbehp** [comment]
And so many others. U+1F595 is a Unicode 7.0 character, and our emoji coverage is based on Unicode 6.x.

**Comment by roubert** [comment]
Yes, my question was essentially "are the new emoji, like U+1F595, available in Noto yet?"

**Comment by dougfelt** [comment]
@roubert, the answer is no, they're not.  Email xiangye for more information.

**Comment by dougfelt** [comment]
"reversed hand with middle finger extended" is now in the emoji set.  enjoy...

**Comment by roubert** [comment]
Verified, and I am enjoying it immensely! 👏
