### ISSUE TITLE
Male cook has wrong skin tones

### ISSUE THREAD

**Issue by Pr0methean** [googlei18n/noto-emoji#125]
The male cook emoji with Fitzpatrick type 1-2 skin (👨🏻‍🍳, U+1F468 U+1F3FB U+200D U+1F373) actually has *darker* skin than the one with type 3 (👨🏼‍🍳, U+1F468 U+1F3FC U+200D U+1F373). Probably the two images need to be swapped.

**Comment by dougfelt** [comment]
So it is.  Thanks for the report.

**Comment by dougfelt** [comment]
Fixed.
