### ISSUE TITLE
Android O Emojis?

### ISSUE THREAD

**Issue by ebraminio** [googlei18n/noto-emoji#141]
I see the SVG folder of this repository is active and updated on the recent days. I wonder if these http://emojipedia.org/google/android-o-beta/ will be uploaded to this repository also or they will not be part of noto project anymore? Thanks

**Comment by dougfelt** [comment]
The current plan is to provide them.  No date for that yet.

**Comment by asturur** [comment]
Better save a copy of the nice blobs :D

2017-05-30 20:28 GMT+02:00 dougfelt <notifications@github.com>:

**Comment by dougfelt** [comment]
:-) I plan to tag the repo before we update to the new design.

**Comment by Peque** [comment]
@dougfelt Could this be reopened so that we have a way to subscribe and get notified when that happens? (and only then close the issue as "resolved")

**Comment by dougfelt** [comment]
Sure.

**Comment by jvschiavo** [comment]
Will they be released this year? Maybe alongside Android O stable?

**Comment by dougfelt** [comment]
That's the plan.

**Comment by 19lmyers** [comment]
Is this repo going to keep the current "blob" design or be replaced with the new design now that Android Oreo is out?

**Comment by dougfelt** [comment]
The repo will have the new design.

**Comment by dougfelt** [comment]
New design has been posted.
