### ISSUE TITLE
Horse racing emoji (U+1F3C7) is missing Fitzpatrick Skin Modifications.

### ISSUE THREAD

**Issue by IcyEyeG** [googlei18n/noto-emoji#143]
https://github.com/googlei18n/noto-emoji/blob/master/svg/emoji_u1f3c7.svg

**Comment by dougfelt** [comment]
Yes, support is a little inconsistent.  We have not planned on further updating this iteration of the emoji design.  When we update the design we will support the 5.0 spec.

**Comment by IcyEyeG** [comment]
Oh ok, no need to sign the CLA and contribute then.

Any idea when the design update will happen?

**Comment by dougfelt** [comment]
If the past is any guide, likely before the end of the year. I can't really be more specific.

**Comment by dougfelt** [comment]
The new designs are available and include skin modifications for the horse racing emoji.
