### ISSUE TITLE
Support Unicode 10 Emoji 5.0

### ISSUE THREAD

**Issue by fujiwarat** [googlei18n/noto-emoji#146]
I think some Unicode glyphs are missed.
U+1F6F7, U+1F6F8, U+1F928 - U+1F92F, U+1F931, U+1F932, U+1F94C, U+1F95F - U+1F96A, U+1F992 - U+1F997, U+1F9D0 - U+1F9E6

Also, emoji variants; U+1F9D2-1F3FB, U+1F9D2-1F3FC, ...
or U+1F3CC-1F3FB-200D-2642-FE0F, U+1F3CC-1F3FC-200D-2642-FE0F, ...

**Comment by fujiwarat** [comment]
I tested NotoColorEmoji.ttf

**Comment by mike-fabian** [comment]
Yes, NotoColorEmoji  still seems to lack all the new Emoji which were added by Unicode 10.0.0.

**Comment by dougfelt** [comment]
Yes, for now they're missing.  We will support the new emoji once the new design is complete and posted.

**Comment by slokhorst** [comment]
Will they be the same as the ones that are currently shipping in Android 8 "Oreo"?

**Comment by dougfelt** [comment]
The new emoji resources (PNG and SVG) are up, as is a font built from the new PNGs.

**Comment by anowlcalledjosh** [comment]
I just downloaded the latest Noto fonts from https://www.google.com/get/noto/, but I don't have either the Android 8.0 or the Emoji 5.0 emoji – do I need to build from source to get these?

**Comment by slokhorst** [comment]
The release at https://www.google.com/get/noto was built on 2017-04-03, so it doesn't contain the new emoji. You should be able to just download https://github.com/googlei18n/noto-emoji/blob/master/fonts/NotoColorEmoji.ttf?raw=true

**Comment by anowlcalledjosh** [comment]
Awesome, thanks!
