### ISSUE TITLE
Need ZWJ sequences for ministers, rabbis and clerics

### ISSUE THREAD

**Issue by Pr0methean** [googlei18n/noto-emoji#147]
Although ZWJ sequences exist in Noto for people of many professions (usually with gender and skin-tone variants), the profession of divinity isn't one of them. I thought of hitting up the Unicode Consortium about this, but they say (http://unicode.org/emoji/selection.html, under H, last bullet point) that for ZWJ sequences -- which are the most backward-compatible way to add minister, rabbi and cleric emoji -- their policy is just to codify what the platform vendors are doing. Thus, it behooves Google as a platform vendor to lead the way on this.

I suggest the following sequences, where {person} means either 👨 (U+1F468, man) or 👩 (U+1F469, woman) or 🧑 (U+1F9D1, androgynous adult), optionally followed by a skin-tone modifier, and ZWJ is the zero-width joiner:

{person}+ZWJ+⛪ = Christian minister
{person}+ZWJ+🕍 = Rabbi
{person}+ZWJ+🕌 = Muslim cleric
{person}+ZWJ+🕉️ = Hindu cleric
{person}+ZWJ+🧘 = Buddhist minister (also called a thera in Thailand?)
{person}+ZWJ+⛩️ = Shinto cleric

**Comment by Pr0methean** [comment]
NB: If they're created, I for one will probably use each of the above emoji at least once in my lifetime, even though I'm an atheist.

**Comment by dougfelt** [comment]
Thanks for the suggestion.

Emoji sequences are standardized by Unicode and we only support emoji that have been standardized at some point.  Proposals for new emoji should be submitted directly to Unicode, see: http://unicode.org/emoji/selection.html
