### ISSUE TITLE
README.md incorrect?

### ISSUE THREAD

**Issue by emuller-amazon** [googlei18n/noto-emoji#148]
The README.md says: "The color version must be built from source.". But it seems that it is present under fonts/NotoColorEmoji.ttf. It seems to have been added recently, so I suspect the README.md is incorrect. Or does the README.md refer to another version of the font?

**Comment by dougfelt** [comment]
Oops, thanks.  You're right, the README should be updated.

**Comment by dougfelt** [comment]
Fixed.
