### ISSUE TITLE
Make it clear that 'make' requires PYTHONPATH to include noto-tools

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-emoji#15]
When I tried to build NotoColorEmoji by running 'make' in the checkout, it failed in 'flag-symlinks' because |GLYPH_NAMES| variable is empty. I couldn't find any issue with rules for that target. Then, it dawned on me that flag_glyph_name.py relies on noto-tools is required by flag_glyph_name.py.  

```
GLYPH_NAMES := $(shell ./flag_glyph_name.py $(FLAGS))
```

`PYTHONPATH={path to noto-tools}:. make` solved the problem. 

I propose that  we either document it more prominently or add a pseudo-target to check if noto_tools is in python path and fails right away (instead of moving forward).

**Comment by dougfelt** [comment]
PYTHONPATH isn't always defined either.  People could use use setup.py in nototools (maybe using 'develop' instead of 'install') and then PYTHONPATH isn't necessary.  That's probably a more likely situation.

I guess flag_glyph+_name failed and the python error got swallowed, so the cause of the failure wasn't clear?  Documentation would certainly help, then.

**Comment by brawer** [comment]
Would it help to make noto-tools a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules)?

**Comment by jungshik** [comment]
It turned out that flag_glyph_name.py does emit an error message, but make did not stop there and the error message scrolled by because 'shell' function takes whatever (empty or not) results comes back. So, if I had redirected a log and looked at it, I'd have more easily noticed it. 

@dougfelt : Anyway, I was thinking of a 'hack' like this in Makefile. Then, nototool-check target will stop make right away where the failure happens instead of 'several screenfuls of log away' :-) 

```
nototool-check: flag_glyph_name.py
        ./flag_glyph_name.py KO > /dev/null
GLYPH_NAMES := $(shell ./flag_glyph_name.py $(FLAGS))

.... snip ...

flag-symlinks: $(WAVED_FLAGS) nototool-check
        $(subst ^, ,                                \
..... snip ...
```

Given that the above is rather hackish, documenting it would be fine. I guess we still need to document even when we do what @brawer suggested.

**Comment by jungshik** [comment]
Close this as a dupe to #8.
