### ISSUE TITLE
List of all supported emojis

### ISSUE THREAD

**Issue by aleki** [googlei18n/noto-emoji#153]
Hi there! Can I get the list of all supported emojis in NotoEmoji-Regular.ttf?

**Comment by dougfelt** [comment]
Here's all the characters, expressed as hex ranges.  Most of these are emoji or components of emoji sequences.

BTW, NotoEmoji has not been updated to track the Unicode releases.  Currently the design effort is focused on the color emoji font.  Unfortunately the color glyphs are bitmap, so don't scale, and also don't always translate well to grayscale or black-and-white.

0000 000d 0020 0023 0030-0039 00a0 00a9 00ae 203c 2049 20e3 2122 2139 2194-2199 21a9-21aa 231a-231b 23e9-23ec 23f0 23f3 24c2 25aa-25ab 25b6 25c0 25ca 25fb-25fe 2600-2601 260e 2611 2614-2615 261d 263a 2648-2653 2660 2663 2665-2666 2668 267b 267f 2693 26a0-26a1 26aa-26ab 26bd-26be 26c4-26c5 26ce 26d4 26ea 26f2-26f3 26f5 26fa 26fd 2702 2705 2708-270c 270f 2712 2714 2716 2728 2733-2734 2744 2747 274c 274e 2753-2755 2757 2764 2795-2797 27a1 27b0 27bf 2934-2935 2b05-2b07 2b1b-2b1c 2b50 2b55 3030 303d 3297 3299 feff 1f004 1f0cf 1f170-1f171 1f17e-1f17f 1f18e 1f191-1f19a 1f1e6-1f1ff 1f201-1f202 1f21a 1f22f 1f232-1f23a 1f250-1f251 1f300-1f320 1f330-1f335 1f337-1f37c 1f380-1f393 1f3a0-1f3c4 1f3c6-1f3ca 1f3e0-1f3f0 1f400-1f429 1f42b-1f43e 1f440 1f442-1f4f7 1f4f9-1f4fc 1f500-1f53d 1f550-1f567 1f5fb-1f640 1f645-1f64f 1f680-1f697 1f699-1f6c5 fe4e5-fe4ee fe82c fe82e-fe837

**Comment by aleki** [comment]
@dougfelt thank you very much!
