### ISSUE TITLE
Android 8.0 Emojis

### ISSUE THREAD

**Issue by jochenschoellig** [googlei18n/noto-emoji#154]
When will there be the new Android 8.0 Oreo Emojis as SVGs available?

Thanks
Jochen

**Comment by dougfelt** [comment]
Not sure yet.  Should be roughly the same time as the PNGs, but there might be a few days delay.

**Comment by jochenschoellig** [comment]
Thank you @dougfelt!

Do you think we are talking about two days or two weeks? ;)

**Comment by PeterBurner** [comment]
Android 8 emojis as SVGs would be great
is there a tool or script to extract them from the TTF file by myself?

**Comment by dougfelt** [comment]
@jochenschoellig  Days, I think.  I'm kind of backed up at the moment.

**Comment by dougfelt** [comment]
@PeterBurner We are not building fonts with SVG resources at the moment, the TTF contains PNGs.

**Comment by jochenschoellig** [comment]
Sorry @dougfelt, do you think that the Emojis will be available on monday? There will be an event where we would like to print with the new emojis. On monday there is the last chance for handing in our files. 😞🙏

PS: Is there a chance that you send me just the ones I need, please?

**Comment by dougfelt** [comment]
Some of the assets didn't convert cleanly to SVG, I need to clean them up first.  I'll see what I can do.

**Comment by dougfelt** [comment]
These (and the PNG) have been posted.

Note:
- A few SVG images (4) contain embedded raster data, we hope to fix these soon.
- The new data does not contain images for emoji we 'alias' to other emoji.  The duplicate (old) images have been removed.  So the emoji set will not appear complete.  It is if you alias the images.  I might check in softlinks to make this easier, but I'm not sure what happens to git users on windows when we have softlinks.
- In the previous set some SVG images contained extraneous parts that lay outside the clipping region.  Most browsers display this fine, but some tools/processes trip over this.  I expect the same issue occurs in the new set but have not examined them.  I haven't had the time to refine tooling to fix this.

**Comment by asturur** [comment]
I really cannot see the PNGs anymore in the repo. Is this normal?

**Comment by PeterBurner** [comment]
great
thanks

**Comment by DeeDeeG** [comment]
> I really cannot see the PNGs anymore in the repo. Is this normal?

As @asturur says, the PNG folder is gone at the moment. Seems they were lost in the shuffle of some recent commits, but they are definitely there if you browse back a few commits.

**Comment by dougfelt** [comment]
Yeah, I screwed up.  They're back now.  Rebuilding the font to make sure I
didn't screw up again.
