### ISSUE TITLE
Color/Regular inconsitency 

### ISSUE THREAD

**Issue by slokhorst** [googlei18n/noto-emoji#163]
The monochrome `NotoEmoji-Regular.ttf` still uses the old "blob-style" emoji, while `NotoColorEmoji.ttf` uses the new "Oreo-style" emoji. Besides the different look, the color version has more complete coverage.

Will the monochrome emoji receive an update, or are they considered obsolete?

**Comment by slokhorst** [comment]
Hm sorry, looks like I didn't search well enough.

From #35:
> Unfortunately, we're not currently budgeted to design full b/w emoji.

So the monochrome are a second-tier, community-supported font.

**Comment by dougfelt** [comment]
> So the monochrome are a second-tier, community-supported font.

Yep, I'm afraid so.

**Comment by slokhorst** [comment]
Thanks for the clarification. 😊
