### ISSUE TITLE
Convert from file name to actual emoji

### ISSUE THREAD

**Issue by asturur** [googlei18n/noto-emoji#172]
Hello this is a sort of help request outside the scope of this repository.

I'm mapping the actual svg files to emoji.
While i have a way to conver from emoji to filename, i m struggling in finding the charsequence / emoji that correspond for example to:

`emoji_u1f9de_200d_2642`

Anyone can give me an hint to figure out how to do it?

**Comment by asturur** [comment]
i m actually taking the name of the emoji:

```
emoji_u1f9db_1f3fc_200d_2642
````

removing the `emoji_u` part. Splitting by `_` and parsing in exadecimal the result.

```
const codepointarray = 'emoji_u1f9db_1f3fc_200d_2642'.replace('emoji_u', '').split('_').map(v => parseInt(v, 16));
```
i get an array 

```
[129499, 127996, 8205, 9794]
```

i try to convert the array

```
String.fromCodePoint(codepointarray)
```

for some emoji work, for many i get:

```
Uncaught RangeError: Invalid code point NaN
    at Function.fromCodePoint (<anonymous>)
    at <anonymous>:1:8
```

**Comment by dougfelt** [comment]
I don't think you can pass an entire array to fromCodePoint, just a single codeepoint.

The following works for me in Chrome:
[129499, 127996, 8205, 9794].map(v => String.fromCodePoint(v)).join('')

**Comment by asturur** [comment]
i would feel dumb to have wasted hours on this, but super happy if it works.

thanks!

**Comment by asturur** [comment]
Totally works.
Thank for help, it was my fault that i took this thing
![image](https://user-images.githubusercontent.com/1194048/30915118-05ac66a6-a396-11e7-8f89-70bc92ba7c2b.png)
as an array.
