### ISSUE TITLE
Anti-Piracy emoji

### ISSUE THREAD

**Issue by FlaggedBrad** [googlei18n/noto-emoji#174]
Could we get an icon for "🕲"? Thanks.

**Comment by dougfelt** [comment]
Unicode doesn't define this as an emoji.  Our policy is to not provide non-emoji characters or sequences in the Noto emoji font except for legacy reasons.  You can petition the unicode emoji committee to enable an emoji presentation for this character.  See http://unicode.org/emoji/selection.html

You can also create your own copy of the font and add whatever you like to it.
