### ISSUE TITLE
"Woman Guard" emoji: hair extends past sides of helmet

### ISSUE THREAD

**Issue by DeeDeeG** [googlei18n/noto-emoji#177]
The hair part of the image is visible extending past the side walls of the helmet, as if the hair is phasing through the helmet material. This affects both PNG and SVG assets for these glyphs. Affects all skin-tone variants, including the "generic/default" (orange) skin tone. (Doesn't affect the male Guard emoji).

Example: 
![Woman Guard with Blondish Hair](https://raw.githubusercontent.com/googlei18n/noto-emoji/fe2ced85011f2c439ae185707859c98676c6ccac/png/128/emoji_u1f482_1f3fc_200d_2640.png)

**Comment by DeeDeeG** [comment]
These appear to have shipped, by the way, because I'm seeing them at [Unicode] and [Emojipedia].

[Unicode]: https://unicode.org/emoji/charts-6.0/full-emoji-list.html#1f482_1f3fc_200d_2640_fe0f
[Emojipedia]: https://emojipedia.org/female-guard-type-3/

**Comment by dougfelt** [comment]
Thanks for the report.

**Comment by dougfelt** [comment]
This is being considered for the next batch of updates/fixes.

**Comment by dougfelt** [comment]
This is fixed.
