### ISSUE TITLE
[Android] "Noto Color Emoji Compat font" doesn't have full icons as Noto Color Emoji ?

### ISSUE THREAD

**Issue by NguyenHoMingle** [googlei18n/noto-emoji#178]
I tried to used the new emoji appcompat library (support verion 26.1.0) It seem to be working but some icons not show in the device HTC One-M8, and i think it is the font NotoColorEmojiCompat.ttf doesn't have enough icons to show ? I tried the icon U+1F576 but the EmojiAppcompatTextview cant show icon. I used the code [new String(Character.toChars(0x1F576));] to create the emoji code. Can you help ?

**Comment by roozbehp** [comment]
Please file a bug against Android Support Library instead. Instruction are at https://source.android.com/source/report-bugs.

/cc @siyamed

**Comment by NguyenHoMingle** [comment]
thank @roozbehp

**Comment by sepehr1014** [comment]
@NguyenHoMingle Have you reported this issue? Couldn't find it.
