### ISSUE TITLE
Can't I simply download fonts?

### ISSUE THREAD

**Issue by OnkelTem** [googlei18n/noto-emoji#182]
Hi!

So I've read the README. Got nototools, installed some dev libs, got fonttools, and now I'm building all this, but another part of me is trying to understand: why couldn't I just download fonts? Would you please uncover this mistery? Not a word in the README about just... getting them. They are fonts, they're always the same, what's the idea behind making a custom build? Just clarify please.

**Comment by DeeDeeG** [comment]
I'm not the maintainer of this repo, but I have an answer for you. The pre-built fonts are in the fonts folder: https://github.com/googlei18n/noto-emoji/tree/master/fonts

or even at this site: https://www.google.com/get/noto/help/emoji/

Maybe the readme can have something like:

"Download the fonts here: [link]"

**Comment by OnkelTem** [comment]
@DeeDeeG Oh, thank you. It was really easy, well... Meanwhile I've built my set of fonts! Waste of energy :)

> "Download the fonts here: [link]"

Yeah, indeed, and to place it somewhere in the top!

**Comment by dougfelt** [comment]
If you just want NotoColorEmoji you can also skip github and instead get it from https://www.google.com/get/noto/.  

Note that some environments don't understand the color font format we use.

It is possible to build a custom emoji font from different images (we do it all the time while developing/reviewing new iterations of the font), but we don't provide documentation for that.

**Comment by OnkelTem** [comment]
> If you just want NotoColorEmoji you can also skip github and instead get it from https://www.google.com/get/noto/.

I needed only this Emoji font since it's missed from Debian and Ubuntu repos. Specifically I was building a docker image for openstreetmap-carto which uses it: https://github.com/gravitystorm/openstreetmap-carto/blob/master/fonts.mss#L118

**Comment by dougfelt** [comment]
Actually, you should update the repos with the version from get/noto.  This version is under review.
