### ISSUE TITLE
Generate PNGs from SVGs during build

### ISSUE THREAD

**Issue by jbicha** [googlei18n/noto-emoji#186]
If I understand correctly, the SVG files are the source for the PNG files.

Please add the script you use to do the SVG-to-PNG conversion to the Makefile.

Optionally, remove the pre-generated PNG files from the repository.

**Comment by dougfelt** [comment]
No, the SVG files are not the source for the PNG files.  The source files are in Adobe Illustrator format and are internal.

We use the PNG files directly in our build tools and have no plans to remove them.
