### ISSUE TITLE
Website says it supports Unicode 9.0 but shouldn't it be 10.0?

### ISSUE THREAD

**Issue by jbicha** [googlei18n/noto-emoji#187]
> Noto Color Emoji supports all emoji defined in the latest Unicode version (v9.0).
 
https://www.google.com/get/noto/help/emoji/

Shouldn't it be 10.0 now?

**Comment by Kanjilearner817** [comment]
It should at least say that it supports all emoji up to Unicode 9.0.

**Comment by dougfelt** [comment]
Yes on both counts.

**Comment by dougfelt** [comment]
Bumped version to 10.0.  I think this should be sufficient.
