### ISSUE TITLE
Please update the fixed images

### ISSUE THREAD

**Issue by theuserbl** [googlei18n/noto-emoji#188]
Here are the emojis with bugs

beer mug:
https://github.com/googlei18n/noto-emoji/blob/master/svg/emoji_u1f37a.svg
https://unicode.org/emoji/charts/full-emoji-list.html#1f37a
https://emojipedia.org/beer-mug/

clinking beer mugs:
https://github.com/googlei18n/noto-emoji/blob/master/svg/emoji_u1f37b.svg
https://unicode.org/emoji/charts/full-emoji-list.html#1f37b
https://emojipedia.org/clinking-beer-mugs/

cheese wedge:
https://github.com/googlei18n/noto-emoji/blob/master/svg/emoji_u1f9c0.svg
https://unicode.org/emoji/charts/full-emoji-list.html#1f9c0
https://emojipedia.org/cheese-wedge/

hambuger:
https://github.com/googlei18n/noto-emoji/blob/master/svg/emoji_u1f354.svg
https://unicode.org/emoji/charts/full-emoji-list.html#1f354
https://emojipedia.org/hamburger/

All buggy emojis are already fixed in Android 8.1.
https://blog.emojipedia.org/google-fixes-burger-emoji/
Please upload the fix here, too.

And it seems, that the noto color emojis are only a subset of Googles Android color emojis.
Will the other emojis also be added in the future or will be the noto emoji list ever be incomplete?

**Comment by dougfelt** [comment]
These are fixed and will be released shortly, once Android is ok with it.

These color emojis are the exact set that are used on Android.  What you might be missing is the fact that in places the same image is used for multiple sequences, see emoji_aliases.txt for the definition.
