### ISSUE TITLE
Design of U+1F92A Grinning Face With One Large and One Small Eye

### ISSUE THREAD

**Issue by Crissov** [googlei18n/noto-emoji#189]
[![&#x1f92a;](https://rawgit.com/googlei18n/noto-emoji/master/png/128/emoji_u1f92a.png)](https://github.com/googlei18n/noto-emoji/blob/master/svg/emoji_u1f92a.svg) U+1F92A `Grinning Face With One Large and One Small Eye` should use the same mouth as either 
[![&#x1f601;](https://rawgit.com/googlei18n/noto-emoji/master/png/128/emoji_u1f601.png)](https://github.com/googlei18n/noto-emoji/blob/master/svg/emoji_u1f601.svg) U+1F601 `Grinning Face With Smiling Eyes` or 
[![&#x1f600;](https://rawgit.com/googlei18n/noto-emoji/master/png/128/emoji_u1f600.png)](https://github.com/googlei18n/noto-emoji/blob/master/svg/emoji_u1f600.svg) U+1F600 `Grinning Face` and 
[![&#x1f929;](https://rawgit.com/googlei18n/noto-emoji/master/png/128/emoji_u1f929.png)](https://github.com/googlei18n/noto-emoji/blob/master/svg/emoji_u1f929.svg) U+1F929 `Grinning Face With Star Eyes`. It should certainly not use the same mouth as 
[![&#x1f62c;](https://rawgit.com/googlei18n/noto-emoji/master/png/128/emoji_u1f62c.png)](https://github.com/googlei18n/noto-emoji/blob/master/svg/emoji_u1f62c.svg) U+1F62C `Grimacing Face`.

Note that in the Noto Color Emoji beta released in May 2017, U+1F601 was erroneously "fixed" to use the gruesome bare-teeth grimace, because Apple used to do the same until iOS 10.2 was released in late 2016.

**Comment by dougfelt** [comment]
Noted.  We're looking at this for the next batch of updates/fixes.

**Comment by dougfelt** [comment]
We use the top version with the tongue sticking out, which (as of today) is consistent with Apple, Twitter, and Samsung, according to emojipedia, though there's still plenty of variation...

https://emojipedia.org/grinning-face-with-one-large-and-one-small-eye/

Closing this as I think we're ok now.
