### ISSUE TITLE
CBDT/CBLC version number

### ISSUE THREAD

**Issue by behdad** [googlei18n/noto-emoji#19]
We use 2.  In OpenType standard they are marked as 3.  I just asked FreeType to add support for 3.  We should update after the fixed version of FreeType is shipped in Android...

**Comment by behdad** [comment]
Or just leave as is...

**Comment by dougfelt** [comment]
@behdad, does this mean we're not technically in agreement with the OT spec?  Is there something to do for this issue?

**Comment by behdad** [comment]
> @behdad, does this mean we're not technically in agreement with the OT spec?

I believe so.  Though, reports say our font works in Windows 10 update, so maybe they also implemented a workaround.

> Is there something to do for this issue?

Yes, after making sure the version of FreeType in Android accepts the correct version number (3), we should bump the version number in the font to 3.

**Comment by behdad** [comment]
I think we should

**Comment by C1710** [comment]
EmojiCompat has some issues with the new version number as it will fail to load the font on devices with Android 4.4 - 6.0.  
It works with the version number set to 2 again.
