### ISSUE TITLE
Required tables "loca" and "glyf" seem missing

### ISSUE THREAD

**Issue by olesalscheider** [googlei18n/noto-emoji#190]
The current Noto Color Emoji font seems to miss the "loca" and "glyf" tables. These are required by the TrueType standard. Poppler checks for these tables and fails to render text if they are not available.

Can you add them to Noto Color Emoji?

**Comment by dougfelt** [comment]
OK.  Note that Noto Color Emoji does not use glyf outlines so this table will be empty.  Poppler needs to be able to use the CBDT compressed (png) data in order to properly use this font.

**Comment by olesalscheider** [comment]
That is ok. The main problem is that Poppler does not render any text anymore with this fontconfig configuration file:

```
<fontconfig>
  <match target="pattern">
    <edit name="family" mode="prepend_first">
      <string>Noto Color Emoji</string>
    </edit>
  </match>
</fontconfig>
```

This is because it tries to load Noto Color Emoji, notices that it does not adhere to the standard, and then renders nothing.

**Comment by jbicha** [comment]
@olesalscheider I don't know much about fontconfig configuration, but why aren't using the upstream configuration? https://cgit.freedesktop.org/fontconfig/tree/conf.d/60-generic.conf

**Comment by olesalscheider** [comment]
It has only been added recently and it gives me a weird mix of different emojis from different fonts.
But this does not change the fact that the Noto Color Emoji font does not adhere to the TrueType standard...

**Comment by dougfelt** [comment]
According to OpenType the glyf table does not appear to be required, and is not used if the font does not use outlines: https://www.microsoft.com/typography/otspec/otff.htm#otttables
This spec lists only cmap, head, hhea, hmtx, maxp, name, OS/2, and post.

While Apple's spec (at https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6.html) appears to, it also includes the line "The "required" tables listed in Table 2 are only required for TrueType fonts."

**Comment by olesalscheider** [comment]
Sorry, I don't know too much about fonts. Does that mean that Noto Color Emoji is only a "sfnt-housed font" and not a TrueType font, as defined in the spec by Apple?
That would mean that these tables are not required and I should fix poppler?

**Comment by anthrotype** [comment]
yes
