### ISSUE TITLE
 Pleading Face emoji [Unicode 11]

### ISSUE THREAD

**Issue by ArmeF97** [googlei18n/noto-emoji#198]
I made this emoji, and it will be encoded
https://emojipedia.org/face-with-pleading-eyes/

I friend of mine designed the emoji for me, and I can use it however I want. I want everyone to use it however they want, so you can have it for your font
https://github.com/ArmeF97/Files/issues/1

**Comment by dougfelt** [comment]
Thanks, but we will be using our own artwork when we support the new emoji.
