### ISSUE TITLE
Multi-Person Groupings are incorrectly gendered

### ISSUE THREAD

**Issue by ojj11** [googlei18n/noto-emoji#201]
According to [UTS #51 2.2.1](https://www.unicode.org/reports/tr51/index.html#Multi_Person_Groupings):

> "the default representation for the characters in the latter group [KISS, COUPLE WITH HEART, FAMILY] should be gender-neutral [...]"

But the code appears to be mapping these emoji to gendered representations (here:)

https://github.com/googlei18n/noto-emoji/blob/6197b23cdac92126883b773d3634a19ceb3c43c8/materialize_emoji_images.py#L33-L35

I realise this is a fairly recent change to the specification (dated 2017-05-18) - will noto-emoji be moving towards gender neutral representations in due course?

**Comment by dougfelt** [comment]
Thanks for the report, we're looking into this.

**Comment by dougfelt** [comment]
These have been updated.
