### ISSUE TITLE
Unicode 11 Emojis

### ISSUE THREAD

**Issue by omkarnathsingh** [googlei18n/noto-emoji#207]
Upstream for Unicode 11 emojis.

**Comment by dougfelt** [comment]
This is a little too cryptic for me to understand.

We will provide Unicode 11 emojis, but generally those don't appear until the Android release containing them has shipped, typically towards the end of the year.

**Comment by omkarnathsingh** [comment]
Okay. I was asking about that only. I will wait for newer ones to appear. Thanks.
