### ISSUE TITLE
Are you planning to update NotoEmoji-Regular.ttf?

### ISSUE THREAD

**Issue by Abz8873** [googlei18n/noto-emoji#211]
NotoEmoji-Regular.ttf has been renewed since December 16, 2016. Do you have any plans to update it following NotoColorEmoji.ttf?

**Comment by DeeDeeG** [comment]
Unless I misunderstand @Abz8873's meaning, this is saying Noto Emoji has been updated at the source repo, but not here.

Basically, my PR adding a few ZWJ sequences to the font (using existing visuals) landed. See this for history of the Noto Emoji source (only 2 commits, one is mine.): https://github.com/googlei18n/noto-source/commits/master/src/NotoEmoji

(Or maybe @Abz8873 is saying that the B/W font is out-of-date, and asking whether it will be updated. In which case my PR at the source repo is tangential to this, and off-topic.)

**Comment by atoponce** [comment]
I think it's that the regular font glyphs do not match the style of the color glyphs, such as here:
![noto](https://user-images.githubusercontent.com/699572/40989517-40965184-68ab-11e8-8aca-4955404a93ac.png)

**Comment by dougfelt** [comment]
We have no plans to update the b/w NotoEmoji-Regular font, unfortunately.
