### ISSUE TITLE
Traffic light emoji are odd colours

### ISSUE THREAD

**Issue by ArloJamesBarnes** [googlei18n/noto-emoji#212]
🚥 (https://github.com/googlei18n/noto-emoji/blob/bf295c4/svg/emoji_u1f6a5.svg) and 🚦 should be green, yellow, red; not blue, yellow, orangered.

This may be due to the Japanese origin of emoji, however:
"Japanese traffic signals mostly follow the same rules [as MUTCD] except that the 'go' signals are referred to as 青 (blue), which they historically were in fact, but this caused complications with the international 'green for go' rule, so in 1973 a decree was issued that the 'go' light should be changed to the bluest possible hue of green, thus making it factually greener without having to change the name from 青 (blue) to 緑 (green)."

Thank you.

**Comment by jbicha** [comment]
I see the correct colors here and at https://www.google.com/get/noto/help/emoji/travel-places.html and https://emojipedia.org/horizontal-traffic-light/

Please provide more information about how exactly you are using the emoji and the operating system version.

**Comment by ArloJamesBarnes** [comment]
Hi @jbicha, I was comparing emojisets on Wikimedia commons with an eye for traffic-related icons, and saw the odd colour, and followed the link to this repository to see if it matched, which it did. I see #40C0E7, #FCC21B, and #ED6C30 in the source.

**Comment by jbicha** [comment]
Please be much more specific.

- What exact web page were you looking at?
- What browser were you using? 
- What operating system version?

Please attach a screenshot too if you can.

**Comment by DeeDeeG** [comment]
The original comment on this issue links to a specific older commit.

That is the KitKat / Lollipop design. More-recent commits show a green/yellow/red coloring as per the Nougat and Oreo redesigns. To get the newer design, view any more-recent commit involving those two SVGs.

https://github.com/googlei18n/noto-emoji/commits/master/svg/emoji_u1f6a5.svg
https://github.com/googlei18n/noto-emoji/commits/master/svg/emoji_u1f6a6.svg

(All the various designs in this repo generally match what was released in Android, and thus far the repo's maintainers have tended not to go back and accept fixes/updates to the visuals, especially if the updated visual is not going to ship in a future version of Android. I would not expect them to add a green version of the KitKat / Lollipop designs in this repo.

I am not one of the maintainers, and I have no official relationship to this project, so take with a grain of salt, I guess?)

**Comment by dougfelt** [comment]
Assuming this is resolved.
