### ISSUE TITLE
Licensing of derived fonts

### ISSUE THREAD

**Issue by C1710** [googlei18n/noto-emoji#214]
First of all - I'm sorry if this is the wrong place to ask this question 😅

So, some months ago, I started making [a fork](https://github.com/c1710/blobmoji) of noto-emoji continuing the Blob emojis.  
From the beginning I wasn't sure about all this licensing stuff so I thought, someone here could help me.  
- First of all - how do I properly implement all the licensing stuff when it comes to the assets? Inside the code I can of course give attribution by only adding the line `modifications (C) 2018...` to the license header, but I don't know about the SVG graphics for example.  
- And what about the font created out of these assets using this software? Noto-Emoji is licensed under the SIL OFL which requires no attribution as far as aI know, but when building my modified/extended font out of the Apache 2.0 licensed files, I would have to ship the Apache 2.0 license which would potentially conflict with the SIL OFL.
- How can I license new emojis which just use the Blob shape and other simple parts of it? ([Example for minor modifications](https://github.com/C1710/blobmoji/blob/master/svg/emoji_u1f9b8.svg), [Example for more modifications](https://github.com/C1710/blobmoji/blob/master/svg/emoji_u1f973.svg))

Some more details for context: I put the whole fork under the Apache 2.0 license as well to avoid any conflicts, but I'd like to contribute fonts built out of it (including an EmojiCompat font) to [a GPL v3.0 project](https://github.com/tuskyapp/Tusky/pull/600) as well.  
And the font would best be licensed on the SIL OFL v1.1 as well.

**Comment by dougfelt** [comment]
Our legal folks say we can't comment on legal issues, unfortunately.  I think you have to ask a lawyer.

**Comment by davelab6** [comment]
Apache 2.0 and gpl v3 are compatible licenses, but you'll need to figure out the details yourself.

If you didn't touch any OFL licensed files, forget about it, it can't possibly be relevant to you. If you did, you might get stuck, because it's perhaps incompatible with all other licenses....
