### ISSUE TITLE
Build font without numbers.

### ISSUE THREAD

**Issue by Xyllon** [googlei18n/noto-emoji#218]
I'm trying to build this font without the inclusion of numbers. I want to replace the Samsung emoji and in short when building it the numbers get spaced out since it uses the numbers built into the emoji font rather than the default font. Deleting the images of the numbers doesn't help as it then just doesn't render them at all. When you use fonttools to get a ttx from the font file it includes entries for numbers even though they're not in the ttx.tmpl of this project. Doing the same with a certain iOS emoji port for Samsung doesn't have these entries so clearly there's some way to achieve it but I have no clue how.

**Comment by dougfelt** [comment]
> Deleting the images of the numbers doesn't help
You probably need to delete the images of the sequences that use the numbers with combining enclosing keycap (0x20e3) as well.  I think if we encounter codepoints in sequences for which we don't have images we synthesize empty glyphs.

**Comment by MKuranowski** [comment]
Hi, I was actually doing the same thing and found a workaround to it, which is IMHO easier than recompiling the ttf file: Use pyftsubset from (fonttools)[https://github.com/fonttools/fonttools].

I use the command `pyftsubset NotoColorEmoji.ttf --output-file=Stripped_NotoColorEmoji.ttf --unicodes-file=codes-no-numbers.txt` — where file codes-no-numbers.txt includes a list of unicode chars that should be included in output font, I've put (my version on a GitHub gist)[https://gist.github.com/MKuranowski/bdbdfb96cf87f6302cd43860aa347163]. This command then creates file Stripped_NotoColorEmoji.ttf without numbers, # and *.

**Comment by Xyllon** [comment]
Much appreciated @MKuranowski. I'd also figured out that you could use extract a ttx file, manually remove mentions of each character you don't want, then remerge it back into the font using `ttx -m [filename.ttf] [filename.ttx]`. A bit of a pain but works.
