### ISSUE TITLE
NotoColorEmoji suport

### ISSUE THREAD

**Issue by Rockingprabhat** [googlei18n/noto-emoji#219]
Below Unicodes are not supporting and coming as Wired Frame.
But when we use Variation selector like \ufe0f it works fine :

\u2639 \u2602 \u270d \u2763 \u26d1d \u2618 \u26f8 \u26f7 \u26f0 \u26e9 \u26f4
\u2708 \u23f1 \u23f2 \u26c8 \u26f1 \u2604 \u2328 \u2709 \u270f \u2712 \u26cf
\u2692 \u2694 \u2699 \u2697 \u2696 \u26d3 \u26b0 \u26b1 \u2622 \u2623 \u21a9
\u21aa \u269b \u2721 \u2638 \u2626 \u262e \u23ed \u23ef \u23ee \u23cf \u269c
\u2611 \u2714 \u2716 \u2695 \u2733 \u2734 \u2747 \u2139 \u25fb \u25fc

**Comment by Rockingprabhat** [comment]
but it shows correctly after using variation selector.

**Comment by dougfelt** [comment]
These characters by default do not use emoji presentation.  I expect your rendering environment is honoring that default by not selecting NotoColorEmoji as the font to use to display them.  The presentation variation selector is telling your rendering environment that you prefer the emoji presentation, and then it is selecting NotoColorEmoji as it indicates that it supports an emoji presentation of these characters.

If you directly use NotoColorEmoji to display these characters without the presentation selector, they should.  This is working as intended.
