### ISSUE TITLE
Puzzle Piece U+1f9e9

### ISSUE THREAD

**Issue by AliceWonderMiscreations** [googlei18n/noto-emoji#223]
This glyph does not appear to be in noto-emoji yet. It's a puzzle piece glyph.

When it is added, I would like to specifically request that it NOT be blue. Here's why.

A blue puzzle piece is the icon of a group called "Autism Speaks" - they chose blue because at one point, it was thought that autism only affected males.

The organization does not have any autistic people on its board, and is widely disliked by people in the autistic community because they present autism as a tragedy and promote many "treatments" that are very harmful to those of us who are autistic, often likely causing PTSD.

Many of their videos are downright disturbing, there is even one suggesting that an autistic child makes a mother want to drive off a cliff killing both herself and the child.

Other videos present autism as something from a horror film that destroys families.

People who are not autistic and do not know the trauma that organization has caused and promotes will often donate to that organization, not realizing that almost none of the money actually goes to anything related to autism - and are likely to use the puzzle piece emoji as a way of suggesting that they "support autism" when in reality they are triggering actual autistic people who have had horrible experiences as a direct result of the "Autism Speaks" organization.

I like puzzles and obviously do not have a problem with a puzzle piece emoji, but please PLEASE do not make it blue. Red or Rainbow or Patterned would be better. Actual puzzle pieces rarely are a single color anyway.

Otherwise many autistic people will be forced to figure out how to use an alternate emoji font to avoid the trigger.

Please see https://learnfromautistics.com/the-problem-with-the-autism-puzzle-piece/

Thank you for your time.

**Comment by AliceWonderMiscreations** [comment]
If by chance you did want an emoji we would enjoy - u1f9e0 is actually close, a rainbow version of that is what we already often use to express neuro-diversity. But that would have to be standardized unless there's already a unicode modifier to rainbow something.

**Comment by dougfelt** [comment]
Our proposed jigsaw puzzle piece design is mixed blue and green and has two pieces at angles to each other.  It seems sufficiently different from the logo of the group you mention.  People might make metaphoric use of this emoji for whatever they want, though.  The page you link to objects to the use of any puzzle piece, however colored, to represent autism, so there's still potential for people to dislike it on these grounds.  Hopefully the fact that our image uses two jigsaw pieces will help avoid this.

There's no standard sequence for a rainbow brain image, but you can propose such a sequence to Unicode.  See https://unicode.org/emoji/proposals.html

**Comment by AliceWonderMiscreations** [comment]
Thank you.
