### ISSUE TITLE
New release for Android Pie?

### ISSUE THREAD

**Issue by jbicha** [googlei18n/noto-emoji#229]
I see that you updated the git repository for Android 9 "Pie" about 10 days ago. I would like to update the [Debian/Ubuntu package](https://tracker.debian.org/pkg/fonts-noto-color-emoji) but I was waiting for a release tag to be pushed first. Is there anything you still need done before pushing the release tag?

**Comment by dougfelt** [comment]
Have been on vacation, and was waiting for some external verification of the font.  Haven't heard anything negative so I will tag it.

**Comment by jbicha** [comment]
Thanks!
