### ISSUE TITLE
Flat Colors

### ISSUE THREAD

**Issue by anasram** [googlei18n/noto-emoji#245]
Hi all, and happy new year to you all. ✨

Considering Material Design principles, isn't Noto Color Emoji font supposed to use flat colors?

**Comment by dougfelt** [comment]
Seeing as these were all drawn by designers employed by and under the direction of Google, apparently not.

**Comment by anasram** [comment]
I definitely realize that I'm talking to Googlers, and that's why I'm submitting this post here!

I'm just expecting to find out why Noto font developers use gradient colors whilst their employer (Google) adopts flat colors in its designs.
