### ISSUE TITLE
Add support for Unicode 7-8 emoji

### ISSUE THREAD

**Issue by webmaven** [googlei18n/noto-emoji#25]
IOS 9.1 has [added support for many emoji](http://emojipedia.org/new-ios-9-1/), especially ones from [Unicode 7](http://emojipedia.org/unicode-7.0/) and [Unicode 8](http://emojipedia.org/unicode-8.0/).

BTW, I think that the lack of support for [Robot Face](http://emojipedia.org/robot-face/) is *particularly* glaring, as it implies a shocking anti-siliconist prejudice. :imp:

**Comment by webmaven** [comment]
@dougfelt, your thoughts?

**Comment by dougfelt** [comment]
The emoji have been updated and now include (most of) the unicode 7 and 8 emoji.

**Comment by webmaven** [comment]
:dancer: :tada: :balloon:
