### ISSUE TITLE
Add/change source SVGs for emoji images added/changed in #28 and #54

### ISSUE THREAD

**Issue by jdherg** [googlei18n/noto-emoji#30]
Bringing the repo up to date with new emoji in #28 is wonderful! It would be great to have the SVGs to match.

Thanks!

**Comment by dann119** [comment]
Good morning, add me to the SVGs request. ;)

**Comment by FiveYellowMice** [comment]
+1

**Comment by Nexan64** [comment]
Would also like to see the SVGs or is there any other way to export them from the font?

**Comment by janmiguelgarcia** [comment]
@Nexan64 We have to wait for the SVGs to be updated. The ttf only contains the PNG versions.

**Comment by dougfelt** [comment]
Unfortunately we don't currently have vector data for about 100 of the current .png images-- we're working on it.

**Comment by raulriera** [comment]
Looks like this is not going to happen. Almost 2 years now

**Comment by asturur** [comment]
is there any chance to get updated svg? even without the missing 100 emoji.

**Comment by dougfelt** [comment]
Most of the SVG have been updated.  There are 54 emoji for which we do not yet have clean SVG, they are listed in the commit message.

**Comment by asturur** [comment]
Looks like flag are still missing or am i wrong?

**Comment by dougfelt** [comment]
Flags are missing.  We don't currently have a mechanism for applying the wave transform.  I believe there are operations in SVG2 that could be applied.  We'd probably also want to standardize the bounding boxes of the SVG and do some other kinds of cleanup.  Personally I would prefer cleanup that was automated so we could continue to take fixes from upstream, rather than forking our source and hand-modifying all of our flag svg.

**Comment by jdherg** [comment]
This is really exciting, thanks @dougfelt ! I see that you opened some bugs for some of the additional SVGs -- do you want to keep this open as a tracking bug for the larger question or close this in favor of a set of smaller, more specific bugs?

**Comment by dougfelt** [comment]
Thanks @jdherg, forgot to close this.  I think the other bugs adequately capture the remaining issues.

**Comment by dougfelt** [comment]
Closing this, separate bugs are probably better to track particular issues.  Some SVG issues have been resolved.  A major unresolved issue is that we don't have flags corresponding to the PNG images because we don't yet have tools to modify the SVG images to apply the wave transform.
