### ISSUE TITLE
NotoEmoji-Regular.ttf is out of date

### ISSUE THREAD

**Issue by Undeterminant** [googlei18n/noto-emoji#35]
Guidelines don't show how we're supposed to go about building this font from source.

**Comment by behdad** [comment]
> Guidelines don't show how we're supposed to go about building this font from source.

We don't have sources for that font as far as I know.

**Comment by brawer** [comment]
@Undeterminant, regarding “building this font from source”, did you perhaps mean NotoColorEmoji? The build instructions would be [here](https://github.com/googlei18n/noto-emoji/blob/master/README.md#building-notocoloremoji).

**Comment by Undeterminant** [comment]
@brawer: I read those instructions. My concern is mostly that the not-colour version is missing glyphs from the colour version.

@behdad: is there a way that we could update with the latest version? Or is it not generated from the colour version?

**Comment by dougfelt** [comment]
It's not generated from the color version.  There is a significant
difference in the repertoires of the two fonts.  The B/W repertoire has not
been updated in some time.

**Comment by Undeterminant** [comment]
Hmm. In that case, it makes sense to either document it as unmaintained or keep this issue open to update it.

**Comment by lonaowna** [comment]
Is there any way to help out with updating the monochrome emoji to have the same coverage as the colored ones? It's a pity it has such limited coverage, especially because most Linux systems cannot render the colored ones (issue #36).

**Comment by aphillips** [comment]
I want to pile on here: I have an application where I need to print emoji in black-and-white. The color version produces grayscaling that I don't want. Worst case, I'd rather have some grayscale glyphs and mostly b&w. But what I don't want are tofus.

**Comment by dougfelt** [comment]
Unfortunately, we're not currently budgeted to design full b/w emoji.  As you point out, rendering color emoji in grayscale often doesn't work well-- the designs often rely on color contrasts that disappear in greyscale.

**Comment by brawer** [comment]
Hello everyone! The history of NotoEmoji-Regular is quite complicated, so we don’t have the original design masters ourselves (long story; and no, we didn’t lose them). Therefore, it has taken us a while to resolve this. But we’ve now converted the font from TrueType into [UFO format](http://unifiedfontobject.org/) and pushed it to [googlei18n/noto-source/src/NotoEmoji](https://github.com/googlei18n/noto-source/tree/master/src/NotoEmoji). Going forward, this will be the official upstream source for this font. If you’d like to add or change a glyph, we’re looking forward to your pull requests; see also the [README](https://github.com/googlei18n/noto-source/blob/master/src/NotoEmoji/README.md).
