### ISSUE TITLE
Ensure emoji flags adhere to unicode spec

### ISSUE THREAD

**Issue by dougfelt** [googlei18n/noto-emoji#39]
See similar issue in behdad/region-flags#8.

"The valid flags used to be less clearly specified, but they are defined in the newest (v2.0) spec, http://unicode.org/reports/tr51/

"ED-14. emoji flag sequence — A sequence of two Regional Indicator characters, where the corresponding ASCII characters are valid region sequences as specified by Unicode region subtags in [CLDR].

"Those Unicode region subtags are based on BCP47, but have some small changes (including http://unicode.org/emoji/charts/full-emoji-list.html#1f1fd_1f1f0."

**Comment by DeeDeeG** [comment]
I found a compact test page for this: 
http://www.unicode.org/emoji/charts/emoji-style.html#emoji_emojifont that actually calls for "Noto Color Emoji" first in the style sheet for the page.

These flags showed as "unknown flag" when I tested:

BL = Saint Barthélemy; BQ = Carribean Netherlands; DG = Diego Garcia; EA = Ceuta & Melilla; EH = Western Sahara; FK = Falkland Islands; GF = French Guiana; GP = Guadeloupe; GS = South Georgia & the South Sandwich Islands; MF = Saint Martin; MQ = Martinique; NC = New Caledonia; PM = Saint Pierre & Miquelon; RE = Réunion; TF = French Southern Territories; WF = Wallis & Futuna; XK = Kosovo; YT = Mayotte

**Comment by dougfelt** [comment]
By default we don't build these for NotoColorEmoji. There's concern that the status of and appropriate flags for these territories are disputed.

I haven't tested this for awhile, but we do have resource data for these based on the wikimedia images and one ought to be able to build a font with them by changing the FLAGS variable to ALL_FLAGS in the Makefile.
