### ISSUE TITLE
Vertical spacing issue on Linux

### ISSUE THREAD

**Issue by Geremia** [googlei18n/noto-emoji#40]
Here are 3 lines of text; line(s) with emojis have a gigantic vertical space on Linux, illustrated by the blue highlighted text:

[![3 lines of text; emojis on line 2 with gigantic vertical space][1]][1]
  [1]: http://i.stack.imgur.com/jX6qs.png

**Comment by dougfelt** [comment]
1) which font is this, and 2) how are you rendering it?

**Comment by Geremia** [comment]
This occurs in Mozilla Thunderbird with both Noto Emoji and Noto Color Emoji.

**Comment by behdad** [comment]
Follow up here: https://bugzilla.mozilla.org/show_bug.cgi?id=1267909
