### ISSUE TITLE
License for pngs and svgs?

### ISSUE THREAD

**Issue by holvonixAdvay** [googlei18n/noto-emoji#45]
The readme says:

   Emoji fonts (under the fonts subdirectory) are under the SIL Open Font License, version 1.1.
   Tools are under the Apache license, version 2.0.

Under which of those licenses (or some other license), are the pngs and svgs?

**Comment by marekjez86** [comment]
Doug, do you know the answer?

**Comment by n7s** [comment]
In any case, outlines derived from font sources under OFL do not inherit that license and can be under any other license you wish. See OFL FAQ item 1.1 and 1.1.1: http://scripts.sil.org/ofl-faq_web#c26665c2

**Comment by holvonixAdvay** [comment]
My question is still directed at Google/the copyright owners, since AFAIK, only the black and white images are in the font file under OFL, and the color ones are not.

**Comment by broadstone** [comment]
Yes, what, precisely, is the license on the source material?

Note that google is also distributing the color version via the public noto website under OFL: https://noto-website.storage.googleapis.com/pkgs/NotoColorEmoji-unhinted.zip

**Comment by dougfelt** [comment]
Apache for the source data.  Flag images are public domain, or copyright-free, there's a list.  I updated the README.md file.
