### ISSUE TITLE
All rights reservered in font header

### ISSUE THREAD

**Issue by grote** [googlei18n/noto-emoji#69]
The header of the produced fonts currently states `Copyright 2015 Google Inc. All Rights Reserved.` which conflicts with the SIL Open Font License, because many rights are not reserved, but granted by the license. The header creates unnecessary legal uncertainty. What is valid, the header or the license file?

I suspect that changing this line to mention the OFL would resolve this issue:
https://github.com/googlei18n/noto-emoji/blob/c6379827aaa9cb0baca1a08a9d44ae74ca505236/NotoColorEmojiSvg.tmpl.ttx#L133

**Comment by dougfelt** [comment]
The "All Rights Reserved" language in the header is meaningless, apparently.  See wikipedia: https://en.wikipedia.org/wiki/All_rights_reserved.

I'll remove it, though.  I'll also use the current nameID 13/14 language we use that references the OFL, this is no longer Apache-licensed.

**Comment by dougfelt** [comment]
Fixed.
