### ISSUE TITLE
Can someone update SVG to Android Nougat7.0

### ISSUE THREAD

**Issue by hpnewf** [googlei18n/noto-emoji#71]
Hello there,

Its really nice to see projects like this on github

Seems  the  SVG's are outdated by a year or so.

Can the Mod /Contributer Kindly update the SVG's to the newest one as shown in Android Nougat 7.0

Awaiting  valued update ASAP

Thanks in advance :-)

**Comment by dougfelt** [comment]
Duplicate of #30

**Comment by dougfelt** [comment]
This is a duplicate of #30
