### ISSUE TITLE
Missing letter in Noto Sans Hebrew

### ISSUE THREAD

**Issue by tsmos** [googlei18n/noto-emoji#74]
The letter 'Chaf sophit' (the 11'th letter's end-of-word form) is missing.

**Comment by dougfelt** [comment]
Can you file this in the noto-fonts repo?  This does not seem to be emoji-related.

**Comment by TidharC** [comment]
@tsmos  please open an issue in the "noto-fonts" repository if you are still experiencing this problem.

If you file a new bug, please state which OS and app you are using (browser, text editor, ...).
