### ISSUE TITLE
ZWJ sequences starting with 'Golfer' (U+1F3CC) are not supported

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-emoji#82]
This is just for the sake of keeping the record. Off-line, I reported this to @dougfelt (after discovering it while testing Noto Color Emoji on CrOS: see https://chromium-review.googlesource.com/#/c/414249/ ) and he found out the root cause as below:

ZWJ sequences starting with 'Golfer' (U+1F3CC) were added to Emoji 4.0 final (they're not included in Emoji 4.0 beta).   Because the latest version of Noto Color Emoji was made based on Emoji 4.0 beta. Those sequences are missing from the font. 

With Noto Color Emoji, those sequences at 
http://unicode.org/emoji/charts/emoji-zwj-sequences.html  (e.g. U+1F3CC U+FE0F U+200D U+2642 U+FE0F ) are not shaped properly by harfbuzz and Chrome. 

/cc @xiangyexiao (fyi)

**Comment by dougfelt** [comment]
This seems to be working in the new design.
