### ISSUE TITLE
Missing flag images (PNG & SVG) other than the first 10

### ISSUE THREAD

**Issue by DeeDeeG** [googlei18n/noto-emoji#84]
I looked into the PNG and SVG folders of this repository, and found only these flags:

🇯🇵 🇰🇷 🇩🇪 🇨🇳 🇺🇸 🇫🇷 🇪🇸 🇮🇹 🇷🇺 🇬🇧

Japan, South Korea, Germany, China, United States, France, Spain, Italy, Russia, United Kingdom.

**Comment by dougfelt** [comment]
That's because the majority of the flags are in third_party/region-flags/png.

**Comment by DeeDeeG** [comment]
Thank you for your response, and for maintaining this repository.

If the cartoon-style flag sources are ever available, please add them to GitHub. They would be very much appreciated.

I note that there is a stylistic difference between the `third_party/region-flags` images:

![thirdparty_region-flags](https://cloud.githubusercontent.com/assets/20157115/22227198/316489b0-e198-11e6-9dd3-10bb042f4c3a.png)

and the cartoon-like style available in the `png` or `svg` folders:

![flags-cartoon](https://cloud.githubusercontent.com/assets/20157115/22229307/e2719246-e1a4-11e6-9fa1-b1bbcf89a6b9.png)

This isn't a problem going forward, in terms of building a complete font.

But as of the moment, a near-complete [Lollipop emoji](https://emojipedia.org/google/android-5.0/) font can be made from the SVGs, other than a majority of the flags not being present. A complete [Nougat](http://emojipedia.org/google/android-7.1/) font can be made from the PNGs, other than the flags and certain ZWJ sequences being missing. So that is why I am requesting in this issue that the cartoon flags be added.

In any case, I thank you all for maintaining this repository, despite how complicated it gets.
