### ISSUE TITLE
Problems building on Linux Mint (build/renamed_flags dir has symlink issues and build fails)

### ISSUE THREAD

**Issue by DeeDeeG** [googlei18n/noto-emoji#85]
Hello. My build keeps failing. I have wiped and re-cloned the whole project several times and I keep getting this problem. This is what I'm seeing:

symbolic links with weird names in `build/renamed_flags`

![strange flag names](https://cloud.githubusercontent.com/assets/20157115/22233706/12e0f8a2-e1c0-11e6-9a17-903645e2ff65.png)

and unusual errors on the commandline: 

(There are consistently eight or so symlinks missing in `renamed_flags` after this error. I don't know what's up with the bogus "directory/symlink/png" that shows up in the error message: 

"ln: failed to create symbolic link 'build/renamed_flags/emoji_nototools/nototools/notoconfig.py.png': No such file or directory")
 
![commandline errors](https://cloud.githubusercontent.com/assets/20157115/22233754/88945d96-e1c0-11e6-8624-e0d118916316.png)

Any ideas of how to make this work?

**Comment by dougfelt** [comment]
That looks odd, no file should be called notoconfig.py.png... Maybe a copy of notoconfig.py got into a directory it doesn't belong in.  Let me take a look.

**Comment by dougfelt** [comment]
I'm not seeing this error.  I created /tmp/emoji-test, cd'd to that directory, cloned googlei18n/noto-emoji, and ran make.

Now, I am not running under virtualenv, and have nototools installed (using 'develop') and also have a notoconfig file in my home directory, so there's still a chance that something in nototools is different, but most of the emoji build is separate from nototools and controlled by the makefile, which should handle this.

I suggest trying over with a clean install of noto-emoji.  Make sure nototools is in a completely separate directory and installed.

**Comment by DeeDeeG** [comment]
A notoconfig file in your home directory? Somehow I've never heard of that.

nototools is in a separate directory, and installed using `python setup.py develop`.

I'm still getting errors. After wiping and cloning fresh I get something about waveflag.c having an incorrect type error.

```
mint@mint-Inspiron-518 ~/GOOGLEi18n $ git clone https://github.com/googlei18n/noto-emoji

Cloning into 'noto-emoji'...
remote: Counting objects: 7662, done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 7662 (delta 19), reused 0 (delta 0), pack-reused 7614
Receiving objects: 100% (7662/7662), 26.97 MiB | 3.82 MiB/s, done.
Resolving deltas: 100% (1063/1063), done.
Checking connectivity... done.

mint@mint-Inspiron-518 ~/GOOGLEi18n $ cd noto-emoji/

mint@mint-Inspiron-518 ~/GOOGLEi18n/noto-emoji $ make -l 90
mkdir -p "build/emoji"
make -C third_party/pngquant
make[1]: Entering directory '/home/mint/GOOGLEi18n/noto-emoji/third_party/pngquant'
./configure

  Compiler: gcc
     Debug: no
       SSE: yes
    OpenMP: no
    libpng: shared (1.2.54)
      zlib: shared (1.2.8)
     lcms2: no

make -C lib static
make[2]: Entering directory '/home/mint/GOOGLEi18n/noto-emoji/third_party/pngquant/lib'
gcc -O3 -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I/usr/include/libpng12  -fexcess-precision=fast   -c -o pam.o pam.c
gcc -O3 -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I/usr/include/libpng12  -fexcess-precision=fast   -c -o mediancut.o mediancut.c
gcc -O3 -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I/usr/include/libpng12  -fexcess-precision=fast   -c -o blur.o blur.c
gcc -O3 -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I/usr/include/libpng12  -fexcess-precision=fast   -c -o mempool.o mempool.c
gcc -O3 -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I/usr/include/libpng12  -fexcess-precision=fast   -c -o viter.o viter.c
gcc -O3 -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I/usr/include/libpng12  -fexcess-precision=fast   -c -o nearest.o nearest.c
gcc -O3 -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I/usr/include/libpng12  -fexcess-precision=fast   -c -o libimagequant.o libimagequant.c
ar rv libimagequant.a pam.o mediancut.o blur.o mempool.o viter.o nearest.o libimagequant.o
ar: creating libimagequant.a
a - pam.o
a - mediancut.o
a - blur.o
a - mempool.o
a - viter.o
a - nearest.o
a - libimagequant.o
make[2]: Leaving directory '/home/mint/GOOGLEi18n/noto-emoji/third_party/pngquant/lib'
gcc -O3 -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I/usr/include/libpng12  -fexcess-precision=fast   -c -o pngquant.o pngquant.c
gcc -O3 -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I/usr/include/libpng12  -fexcess-precision=fast   -c -o rwpng.o rwpng.c
gcc pngquant.o rwpng.o -lm lib/libimagequant.a -lpng12 -lz -lm -o pngquant
make[1]: Leaving directory '/home/mint/GOOGLEi18n/noto-emoji/third_party/pngquant'
mkdir -p "build/quantized_pngs"
using optipng
mkdir -p "build/compressed_pngs"
cc waveflag.c -o waveflag -std=c99 -Wall -Wextra `pkg-config --cflags --libs cairo` -lm `pkg-config --libs cairo`
waveflag.c: In function ‘wave_flag’:
waveflag.c:414:24: warning: passing argument 1 of ‘__xpg_basename’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  strcat (out, basename(filename));
                        ^
In file included from waveflag.c:20:0:
/usr/include/libgen.h:34:14: note: expected ‘char *’ but argument is of type ‘const char *’
 extern char *__xpg_basename (char *__path) __THROW;
              ^
mkdir -p "build/flags"
mkdir -p "build/resized_flags"
mkdir -p "build/renamed_flags"
^CMakefile:155: recipe for target 'build/flags/HK.png' failed
make: *** [build/flags/HK.png] Interrupt
```

**Comment by dougfelt** [comment]
This is a warning and I've been seeing it too.  The font should build fine despite it.

**Comment by DeeDeeG** [comment]
I started fresh on another install of Linux Mint I had around, but got the same error as comment 1 of this issue.

I'm starting to suspect this is specific to Linux Mint, or to machines where Android Studio is also installed. Both machines I have tried this on were Linux Mint 18.1 MATE Edition 64-bit, and coincidentally had Android Studio installed before trying to build noto-emoji from github sources. (still too many variables to know what is the main issue).

Also not sure if it's a problem to get fonttools via `sudo pip install fonttools` or if I need to install from the github repository source?

And one other possibility, if the notoconfig file you mentioned having in your home directory is important, I am 99% sure I do not have that.

So far here's what I've done:

- `git clone https://github.com/googlei18n/nototools/`

- `cd nototools`

- `sudo pip install setuptools`
(needed in order to run `python setup.py develop`)

- `sudo python setup.py develop` 

-  get optipng from here: http://optipng.sourceforge.net/
(I got optipng-0.7.6.tar.gz)
extract to `~/optipng-0.7.6`

- `cd ~/optipng-0.7.6/`
 `./configure`
 `make`
 `make test`
 `sudo make install`

- `pip install fonttools`
(says I already have dependency fonttools satisfied)

- `cd ~/`
`git clone https://github.com/googlei18n/noto-emoji/`

- `cd noto-emoji`
`make`
(build fails, needs libpng-dev to run)

- `sudo apt-get install libpng-dev`
(actually installs `libng12-dev` instead)

- `make`
(build fails, needs cairo to run)

- `sudo apt-get install libcairo-dev`
 (actually installs `libcairo2-dev` instead, along with a bunch of libcairo2-dev dependencies)

- `make`
(fails with segfault due to errors in waveflag.c)

```
mint@mint-AO722 ~/noto-emoji $ make -l 90
using optipng
cc waveflag.c -o waveflag -std=c99 -Wall -Wextra `pkg-config --cflags --libs cairo` -lm `pkg-config --libs cairo`
waveflag.c: In function ‘wave_flag’:
waveflag.c:411:15: warning: implicit declaration of function ‘basename’ [-Wimplicit-function-declaration]
  strcat (out, basename(filename));
               ^
waveflag.c:411:15: warning: passing argument 2 of ‘strcat’ makes pointer from integer without a cast [-Wint-conversion]
In file included from waveflag.c:24:0:
/usr/include/string.h:133:14: note: expected ‘const char * restrict’ but argument is of type ‘int’
 extern char *strcat (char *__restrict __dest, const char *__restrict __src)
              ^
mkdir -p "build/flags"
mkdir -p "build/resized_flags"
mkdir -p "build/renamed_flags"
Segmentation fault
Makefile:157: recipe for target 'build/flags/AC.png' failed
make: *** [build/flags/AC.png] Error 139

```
going out on a limb here, after reading the diff from the latest commit of `waveflag.c`...

- manually re-add line "`#include <libgen.h>`" to beginning of waveflag.c

- `make`
build fails with same error as in the first comment of this thread.

**Comment by dougfelt** [comment]
Sorry,  and thanks for catching that and reporting these problems.  I inadvertently removed the header needed by basename when merging, I fixed that.  (Also this header probably needs to be changed since it's the origin of the warning we're seeing when building waveflag.c).

Also of course we need to fix/document the dependencies for cairo et. al.

It looks like flag_glyph_name.py is loading add_emoji_gsub which is loading nototools.font_data which is loading notoconfig.py which is emitting an error message to the shell, which is getting picked up by the code for FLAG_GLYPH_NAMES and turned into a name of a flag file (the bogus name 'build/renamed_flags/emoji_nototools/nototools/notoconfig.py.png').  The immediate workaround is to put a file named '.notoconfig' in your home directory, but really I need to remove the message notoconfig.py spits out, you shouldn't need this.

**Comment by DeeDeeG** [comment]
No problem, I understand how these things can be. And more testers means fewer unreported bugs! That's why I'm posting here, to help the project.

I tried it again with an empty `.notoconfig` file in my home directory, and it indeed works.
